name: Run tests

on:
  push:
    branches:
      - master 
      
jobs:
  test:
    runs-on: ubuntu-latest 

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run test script
        run: pwd
        run: ll
        run: chmod +x ../../test_gcd.sh
        run: bash ../../test_gcd.sh
